### PR TITLE
Profile pr21 30

### PR DESCRIPTION
**Pull request by AntMousinho**
- [creating feedbackQuotes table and associations](https://dfacademy.atlassian.net/browse/PR21-30)
- [writing tests for post requests](https://dfacademy.atlassian.net/browse/PR21-37)
- [feedback controller handles post requests](https://dfacademy.atlassian.net/browse/PR21-35)

Able to handle a post request that creates a new FeedbackQuote that is associated with the chosen User (one to many relationship). 

Also created an ApiExceptionHandler and 2 custom Exceptions for use in RestControllers. Information about why we added this, how they work, and how anyone can use them can be found in the docs folder.

### CODE REVIEW

**Review by dearshrewdwit — CHANGES_REQUESTED** [review]
Lots of great work in here. Nice job. Custom error classes! 

I like that you've tried to solve the problem of database cleaning before each test by using sql files in `src/main/resources` and `@Sql` annotations. 

This becomes problematic the larger the codebase becomes however - the same sql file will become larger and larger as different areas of the codebase need different initial state for tests.

You could break up the data sql file into specific sql instructions to create a user for example, a user with feebackquotes, etc. 

Or better yet you can autowire the models and repositories into the test files and create the specific db test state that you need in a before hook for each test.

You can keep the truncate script to clean the tables after every test method (or use flyway to clean/migrate for every test)

**Comment by AntMousinho** [comment]
I've made one commit where I have broken up the sql file into smaller, more specific instructions.

In the most recent commit I have fed the data into the database using models and repositories in the beforeEach statement. I'd just like to check if the way I've done it was what you had in mind, or if there was a better way I couldn't figure out?

testing

**Comment by dearshrewdwit** [comment]
> I've made one commit where I have broken up the sql file into smaller, more specific instructions.
> 
> In the most recent commit I have fed the data into the database using models and repositories in the beforeEach statement. I'd just like to check if the way I've done it was what you had in mind, or if there was a better way I couldn't figure out?
> 
> testing

@AntMousinho Correct. Now it's clearer reading the test what the set up is, what's being executed, and what's being asserted on. Nice job. 

Do you use the SQL statements anywhere now?

**Comment by AntMousinho** [comment]
No need for the SQL statements anymore, I'll quickly replace it with flyway clean and migrate

**Comment by dearshrewdwit** [comment]
> No need for the SQL statements anymore, I'll quickly replace it with flyway clean and migrate

I like the truncate script - it'll be quicker rather than dropping,creating,migrating

**Review by dearshrewdwit — APPROVED** [review]

**Review by ndowkunda — APPROVED** [review]

**Pull request merged**
